#!/usr/bin/env python3
"""Build deterministic portable archives and a standalone chat prompt (Python 3.10+)."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import sys
import zipfile

from validate import (
    LINK_RE, ROOT, SKILL_REL, local_target, parse_frontmatter, source_files, validate,
)

DEFAULT_VERSION = "1.0.0"
ZIP_TIMESTAMP = (2020, 1, 1, 0, 0, 0)


def write_zip(destination: Path, entries: dict[str, bytes]) -> None:
    """Stored entries avoid compressor-version differences across Python runtimes."""
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_STORED) as archive:
        for name, data in sorted(entries.items()):
            info = zipfile.ZipInfo(name, date_time=ZIP_TIMESTAMP)
            info.compress_type = zipfile.ZIP_STORED
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            archive.writestr(info, data)


def normalized_bytes(path: Path) -> bytes:
    # Git checkouts can use CRLF on Windows. Archive bytes remain identical.
    return path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n").encode("utf-8")


def portable_prompt(root: Path) -> str:
    skill = root / SKILL_REL
    entrypoint = skill / "SKILL.md"
    fields, body = parse_frontmatter(entrypoint.read_text(encoding="utf-8"))
    references = sorted((skill / "references").rglob("*.md"))
    section_names = {entrypoint.resolve(): "Core instructions"}
    section_names.update({path.resolve(): f"Reference: {path.relative_to(skill).as_posix()}" for path in references})

    def flatten(path: Path, text: str) -> str:
        # The surrounding section supplies the title; retain all actual rules.
        text = re.sub(r"\A# [^\n]+\n+", "", text, count=1)

        def replace_link(match: re.Match[str]) -> str:
            target = local_target(path, match.group(1))
            if target not in section_names:
                return match.group(0)
            label = re.match(r"!?\[([^\]]*)\]", match.group(0)).group(1)
            return f'{label} (see "{section_names[target]}")'

        text = LINK_RE.sub(replace_link, text)
        # References named in code spans remain usable when no files exist.
        def replace_reference(match: re.Match[str]) -> str:
            target = (path.parent / match.group(1)).resolve()
            if target in section_names:
                return f'"{section_names[target]}"'
            return match.group(0)

        text = re.sub(r"`((?:\.?\.?/)*references/[^`\n]+\.md)`", replace_reference, text)
        # Nest headings while preserving fenced examples exactly.
        lines = []
        fence_char = ""
        fence_length = 0
        for line in text.splitlines():
            fence = re.match(r"^\s{0,3}(`{3,}|~{3,})", line)
            if fence:
                marker = fence.group(1)
                if not fence_char:
                    fence_char, fence_length = marker[0], len(marker)
                elif marker[0] == fence_char and len(marker) >= fence_length:
                    fence_char = ""
            if not fence_char and not fence:
                line = re.sub(r"^(#{1,5}) ", r"#\1 ", line)
            lines.append(line)
        return "\n".join(lines).strip()

    parts = [
        "# Chtets portable prompt",
        "> Generated by `python scripts/package.py`. Edit the source skill and references, then rebuild.",
        "Paste or attach this document in a chat app and ask the agent to use Chtets for your writing task. "
        "This is a manual prompt, not native automatic skill installation. "
        "The app's instruction hierarchy, context limits and available tools still apply.",
        "All core instructions and reference texts are included below. "
        "When an instruction says to read or load a reference, use the corresponding included section. "
        "No local files or skill-discovery tools are needed. "
        "Apply the relevant genre and language guidance; do not turn every short task into a full audit.",
        f"Purpose: {fields['description']}",
        "## Core instructions",
        flatten(entrypoint, body),
    ]
    for path in references:
        parts.extend(["---", f"## {section_names[path.resolve()]}", flatten(path, path.read_text(encoding="utf-8"))])
    return "\n\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help="repository root")
    parser.add_argument("--version", default=DEFAULT_VERSION, help="release version, without a v prefix")
    args = parser.parse_args()
    if not re.fullmatch(r"\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?", args.version):
        parser.error("--version must be a semantic version such as 1.0.0")
    root = args.root.resolve()
    errors = validate(root)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    prompt = root / "docs/portable-prompt.md"
    prompt.write_text(portable_prompt(root), encoding="utf-8", newline="\n")
    errors = validate(root, require_prompt=True)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    output = root / "dist"
    output.mkdir(exist_ok=True)
    skill = root / SKILL_REL
    skill_entries = {
        "chtets/" + path.relative_to(skill).as_posix(): normalized_bytes(path)
        for path in source_files(root) if path.is_relative_to(skill)
    }
    skill_entries["chtets/LICENSE"] = normalized_bytes(root / "LICENSE")
    source_entries = {
        "chtets-source/" + path.relative_to(root).as_posix(): normalized_bytes(path)
        for path in source_files(root)
    }
    archives = [
        (output / f"chtets-v{args.version}.zip", skill_entries),
        (output / f"chtets-source-v{args.version}.zip", source_entries),
    ]
    checksums = []
    for destination, entries in archives:
        write_zip(destination, entries)
        digest = hashlib.sha256(destination.read_bytes()).hexdigest()
        checksums.append(f"{digest}  {destination.name}")
        print(f"Built {destination.relative_to(root)} ({len(entries)} files)")
    (output / "SHA256SUMS").write_text("\n".join(checksums) + "\n", encoding="utf-8", newline="\n")
    print("Generated docs/portable-prompt.md and dist/SHA256SUMS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
